name: Sanity Check

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Env Setup
      run: |
        npm install --save-dev
    
    - name: Unit Tests
      run: |
        npm run test
    
    - name: Lint Check
      run: |
        npm run lint
    
    - name: Build Sanity Test
      run: |
        npm run build
